services:
  process-manager:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: process-manager
    image: process-manager:latest
    stdin_open: true
    tty: true
    working_dir: /app
    entrypoint: ["process_manager"]
    restart: "no"
